import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F2F2F2" },
  navbar: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 20,
    paddingTop: 50,
  },
  navIcon: { fontSize: 28 },
  titleText: {
    fontSize: 30,
    textAlign: "center",
    marginVertical: 20,
    fontFamily: "serif",
  },
  scrollContent: { alignItems: "center", paddingBottom: 100 },
  petCard: {
    flexDirection: "row",
    backgroundColor: "#D9D9D9",
    borderRadius: 50,
    width: "85%",
    height: 100,
    alignItems: "center",
    marginBottom: 20,
    padding: 10,
  },
  petImage: { width: 80, height: 80, borderRadius: 40, borderWidth: 1 },
  petInfo: { marginLeft: 15 },
  petName: { fontSize: 20, fontWeight: "bold" },
  searchCircle: {
    backgroundColor: "#E6B5B5",
    width: 150,
    height: 150,
    borderRadius: 75,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  searchText: { textAlign: "center", fontWeight: "bold" },
  addButton: {
    backgroundColor: "#E6B5B5",
    width: 80,
    height: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 20,
  },
  addIcon: { fontSize: 30, fontWeight: "bold" },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: 70,
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabIconImg: { width: 40, height: 40, resizeMode: "contain" },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
});
