import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F2F2F2",
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  backText: {
    color: "white",
    fontSize: 20,
  },
  titleText: {
    fontSize: 30,
    textAlign: "center",
    marginVertical: 20,
    fontFamily: "serif",
    marginTop: 60,
  },
  scrollContent: {
    alignItems: "center",
    paddingBottom: 100,
    paddingHorizontal: 15,
  },
  paseadorCard: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 15,
    width: "95%",
    height: 140,
    alignItems: "center",
    marginBottom: 20,
    padding: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 5,
  },
  paseadorImage: {
    width: 110,
    height: 110,
    borderRadius: 55,
    marginRight: 15,
    borderWidth: 2,
    borderColor: "#E6B5B5",
  },
  paseadorInfo: {
    flex: 1,
    justifyContent: "center",
  },
  paseadorName: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 8,
  },
  serviceType: {
    fontSize: 14,
    color: "#666",
    fontWeight: "600",
  },
  starsContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  star: {
    fontSize: 16,
    color: "#FFD700",
    marginRight: 2,
  },
  halfStar: {
    fontSize: 16,
    color: "#FFD700",
    marginRight: 2,
  },
  emptyStar: {
    fontSize: 16,
    color: "#CCCCCC",
    marginRight: 2,
  },
  ratingText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    marginLeft: 5,
  },
  bottomTab: {
    flexDirection: "row",
    backgroundColor: "#99D9C1",
    height: 70,
    position: "absolute",
    bottom: 0,
    width: "100%",
    justifyContent: "space-around",
    alignItems: "center",
  },
  tabItem: {
    alignItems: "center",
    justifyContent: "center",
  },
  tabLabel: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
  tabIconImg: {
    width: 40,
    height: 40,
    resizeMode: "contain",
  },
});
