import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  backButton: {
    position: "absolute",
    top: 50,
    left: 20,
    zIndex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 20,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  backText: {
    color: "white",
    fontSize: 20,
  },
  scrollContent: {
    alignItems: "center",
    paddingTop: 100,
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  ofertaImage: {
    width: 200,
    height: 200,
    borderRadius: 15,
    marginBottom: 20,
    borderWidth: 3,
    borderColor: "#dc3545",
  },
  ofertaName: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 10,
  },
  flashBadge: {
    backgroundColor: "#dc3545",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: "#fff",
    shadowColor: "#dc3545",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  flashText: {
    color: "white",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
  },
  priceContainer: {
    marginBottom: 20,
    alignItems: "center",
    flexDirection: "column",
  },
  precioOriginal: {
    fontSize: 18,
    color: "#999",
    textDecorationLine: "line-through",
    marginBottom: 5,
  },
  precio: {
    fontSize: 40,
    fontWeight: "bold",
    color: "#28a745",
  },
  detailsContainer: {
    width: "100%",
    backgroundColor: "white",
    borderRadius: 10,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginBottom: 20,
  },
  detailLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#555",
    marginTop: 10,
  },
  detailValue: {
    fontSize: 16,
    color: "#333",
    marginBottom: 5,
    lineHeight: 24,
  },
  stockValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#28a745",
    marginBottom: 5,
  },
  tiempoValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#dc3545",
    marginBottom: 5,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 20,
  },
  comprarButton: {
    backgroundColor: "#dc3545",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    marginRight: 10,
  },
  compartirButton: {
    backgroundColor: "#17a2b8",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    flex: 1,
    marginLeft: 10,
  },
  buttonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
});
